// Code generated by "stringer -type=DelayEventState"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WaitingForInitialConnect-0]
	_ = x[Connected-1]
	_ = x[Disconnected-2]
	_ = x[Completed-3]
	_ = x[Replaced-4]
}

const _DelayEventState_name = "WaitingForInitialConnectConnectedDisconnectedCompletedReplaced"

var _DelayEventState_index = [...]uint8{0, 24, 33, 45, 54, 62}

func (i DelayEventState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DelayEventState_index)-1 {
		return "DelayEventState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DelayEventState_name[_DelayEventState_index[idx]:_DelayEventState_index[idx+1]]
}
