// Code generated by "stringer -type=DelayedEventSignal"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ParticipantConnected-0]
	_ = x[ParticipantLookupSuccessful-1]
	_ = x[ParticipantDisconnectedIntentionally-2]
	_ = x[ParticipantConnectionAborted-3]
	_ = x[DelayedEventReset-4]
	_ = x[DelayedEventTimedOut-5]
	_ = x[DelayedEventNotFound-6]
	_ = x[WaitingStateTimedOut-7]
	_ = x[SFUNotAvailable-8]
}

const _DelayedEventSignal_name = "ParticipantConnectedParticipantLookupSuccessfulParticipantDisconnectedIntentionallyParticipantConnectionAbortedDelayedEventResetDelayedEventTimedOutDelayedEventNotFoundWaitingStateTimedOutSFUNotAvailable"

var _DelayedEventSignal_index = [...]uint8{0, 20, 47, 83, 111, 128, 148, 168, 188, 203}

func (i DelayedEventSignal) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DelayedEventSignal_index)-1 {
		return "DelayedEventSignal(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DelayedEventSignal_name[_DelayedEventSignal_index[idx]:_DelayedEventSignal_index[idx+1]]
}
