server_name: "synapse.e2e.test"
public_baseurl: http://synapse.e2e.test/

pid_file: /tmp/homeserver.pid

listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    # Some Docker setups disable IPv6 on the container's network interface,
    # which otherwise leaves the default dual-stack bind reachable only via
    # loopback.
    bind_addresses: ["0.0.0.0"]
    resources:
      - names: [client]
        compress: false

database:
  name: sqlite3
  args:
    database: /tmp/homeserver.db

media_store_path: /tmp
signing_key_path: "/tmp/homeserver.signing.key"

report_stats: false

app_service_config_files:
  - /config/app-service.yaml

# Enable registration so that the test suite can provision its own users.
enable_registration: true
enable_registration_without_verification: true

experimental_features:
  # Enable membership look-up via /is_joined.
  msc4502_enabled: true
  # Enable C-S & S-S request proxying for application services.
  msc4512_enabled: true
