name: Build

on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    name: Docker
    permissions:
      contents: write
      packages: write
      id-token: write
    uses: ./.github/workflows/docker.yaml
    secrets:
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_AUDIENCE: ${{ secrets.TS_AUDIENCE }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      docker_tags: |
        type=sha,format=short,event=branch
        type=ref,event=pr
        type=semver,pattern={{version}}
        type=raw,value=latest-ci_{{date 'X'}},enable={{is_default_branch}}
        latest-ci
