name: Lint

on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  lint:
    timeout-minutes: 15
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@4be7066ada62dd38de10e7b70166bc74ed198c30 # stable
        with:
          components: rustfmt, clippy
      - name: Cache Rust build artifacts
        uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae # v2
      - name: rustfmt
        run: cargo fmt --check
      - name: clippy
        run: cargo clippy --all-targets --locked -- -D warnings
