name: Lint

on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  lint:
    timeout-minutes: 15
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # v1
        with:
          components: rustfmt, clippy
      - name: Cache Rust build artifacts
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
      - name: rustfmt
        run: cargo fmt --check
      - name: clippy
        run: cargo clippy --all-targets --locked -- -D warnings
